table Fact_受注見込
	lineageTag: 28c24dea-c28c-5a89-8c4c-990df4fadce9

	measure 確定金額 = CALCULATE(SUM('Fact_受注見込'[金額]), 'Fact_受注見込'[区分種別] = "確定")
		formatString: #,##0
		lineageTag: d147cfbb-2cfe-5ffe-9cd1-d7958d9ac412

	measure 内示金額 = CALCULATE(SUM('Fact_受注見込'[金額]), 'Fact_受注見込'[区分種別] = "内示")
		formatString: #,##0
		lineageTag: 2b29fadd-8dbd-5eb8-8947-649c903e450f

	measure 内示＋確定 = [確定金額] + [内示金額]
		formatString: #,##0
		lineageTag: 52b92ab7-c39e-5b5e-a862-b7efe00b7514

	measure 予算額 = SUM('Fact_予算'[予算金額])
		formatString: #,##0
		lineageTag: 93c3d141-d27d-55f7-9c09-6f029fe7fb68

	measure 達成率 = DIVIDE([内示＋確定], [予算額])
		formatString: 0.0%
		lineageTag: 9d5e9403-9213-5662-8235-9ac388ba471b

	measure 予算差額 = [内示＋確定] - [予算額]
		formatString: #,##0
		lineageTag: 780f1d8b-66b0-578e-9715-8576c8481856

	measure 確定数量 = CALCULATE(SUM('Fact_受注見込'[数量]), 'Fact_受注見込'[区分種別] = "確定")
		formatString: #,##0
		lineageTag: c329c5e6-f42f-5c75-9942-8b0f4a7e7648

	measure 内示数量 = CALCULATE(SUM('Fact_受注見込'[数量]), 'Fact_受注見込'[区分種別] = "内示")
		formatString: #,##0
		lineageTag: ecca3193-d54d-5c15-86b5-42460bc2f690

	measure データ基準日 = FORMAT(MAX('Fact_受注見込'[基準日]), "yyyy/mm/dd")
		lineageTag: 2dea6055-b911-5bf8-aaf4-232e6a884c92

	measure 見込金額 = CALCULATE(SUM('Fact_受注見込'[金額]), 'Fact_受注見込'[区分種別] = "見込")
		formatString: #,##0
		lineageTag: c4965344-33a6-53b5-8385-6d8256d3b63e

	measure 内示＋確定＋見込 = [内示＋確定] + [見込金額]
		formatString: #,##0
		lineageTag: b8e90e8e-9003-5f2c-89c1-082780bd95cc

	measure 達成率_見込含む = DIVIDE([内示＋確定＋見込], [予算額])
		formatString: 0.0%
		lineageTag: 7e485752-1df2-5931-bd2f-e0b213874fda

	column 年月
		dataType: string
		lineageTag: 25a7181a-2d2a-55f5-a8b9-d5772b8fc2c6
		summarizeBy: none
		sourceColumn: 年月

		annotation SummarizationSetBy = Automatic

	column 区分種別
		dataType: string
		lineageTag: 461255e8-265b-58b4-ac16-ecb42c982e69
		summarizeBy: none
		sourceColumn: 区分種別

		annotation SummarizationSetBy = Automatic

	column 計画区分
		dataType: string
		lineageTag: 4c1911b3-a0c6-53cd-81e3-cd9612589290
		summarizeBy: none
		sourceColumn: 計画区分

		annotation SummarizationSetBy = Automatic

	column 得意先番号
		dataType: string
		lineageTag: 3b22c0eb-d342-5bbf-add7-ad160e6fe8fe
		summarizeBy: none
		sourceColumn: 得意先番号

		annotation SummarizationSetBy = Automatic

	column 得意先キー
		dataType: string
		lineageTag: b5f5fbca-78bd-50fc-a5fa-1b141e23fce0
		summarizeBy: none
		sourceColumn: 得意先キー

		annotation SummarizationSetBy = Automatic

	column 品目コード
		dataType: string
		lineageTag: 96f444ba-98ac-5fef-8c14-a072a49fd2ef
		summarizeBy: none
		sourceColumn: 品目コード

		annotation SummarizationSetBy = Automatic

	column 数量
		dataType: double
		formatString: #,##0
		lineageTag: 69389704-9ef7-578c-a20a-df06ebb2043d
		summarizeBy: sum
		sourceColumn: 数量

		annotation SummarizationSetBy = Automatic

	column 単価
		dataType: double
		formatString: #,##0.00
		lineageTag: 24a6542e-0840-5520-b88a-56b390b12d68
		summarizeBy: none
		sourceColumn: 単価

		annotation SummarizationSetBy = Automatic

	column 金額
		dataType: double
		formatString: #,##0
		lineageTag: 9679ef03-c474-53db-b639-99d2d283c6a3
		summarizeBy: sum
		sourceColumn: 金額

		annotation SummarizationSetBy = Automatic

	column 基準日
		dataType: dateTime
		formatString: yyyy/MM/dd
		lineageTag: 33ca9ff2-a7f7-5a92-9d30-85c7c9314d28
		summarizeBy: none
		sourceColumn: 基準日

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 得意先区分 = RELATED('Dim_得意先'[得意先区分])
		dataType: string
		lineageTag: c5440603-dfda-5085-a1b5-24c1b6271ac6
		summarizeBy: none
		sortByColumn: 得意先区分順序

		annotation SummarizationSetBy = Automatic

	column 得意先区分順序 = RELATED('Dim_得意先'[得意先区分順序])
		dataType: int64
		isHidden
		lineageTag: a821c137-38ca-5efb-a437-b847d44bdb6b
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 在庫品目コード
		dataType: string
		lineageTag: 1b514575-1407-5498-b92c-d1749ed86c2c
		summarizeBy: none
		sourceColumn: 在庫品目コード

		annotation SummarizationSetBy = Automatic

	column 集計に含める
		dataType: string
		lineageTag: 6960a1ac-a367-5293-ae6e-aa7002400d53
		summarizeBy: none
		sourceColumn: 集計に含める

		annotation SummarizationSetBy = Automatic

	partition Fact_受注見込 = m
		mode: import
		source =
				let
				    Raw = Value.NativeQuery(Oracle.Database("(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=banshu-srv)(PORT=1521))(CONNECT_DATA=(SERVICE_NAME=prones)))"), "SELECT * FROM ( WITH px AS ( SELECT TRIM(F_納入品目番号) AS 品目, TRIM(F_得意先番号) AS 得意先, F_開始日 AS 開始日, F_契約単価 AS 単価 FROM PRONES.TB_納入品目得意先単価情報 WHERE F_納入品目番号 >= '0' AND TRANSLATE(F_開始日,'0123456789','9999999999') = '9999/99/99' ), rng AS ( SELECT TO_CHAR(TRUNC(SYSDATE,'YYYY'),'YYYY/MM') AS 実績開始, TO_CHAR(TRUNC(SYSDATE,'YYYY'),'YYYY/MM') AS 出力開始, TO_CHAR(ADD_MONTHS(TRUNC(SYSDATE,'MM'),13),'YYYY/MM') AS 出力終了 FROM DUAL ), cal AS ( SELECT TO_CHAR(F_年月日,'YYYY/MM') AS 月, COUNT(*) AS 稼働日 FROM PRONES.TB_カレンダ情報 WHERE F_稼働区分 = '0' GROUP BY TO_CHAR(F_年月日,'YYYY/MM') ), 内示最新作成日 AS ( SELECT F_得意先, MAX(F_作成日) AS F_作成日 FROM PRONES.TB_統合計画日別情報 WHERE F_納入品目番号 > '0' GROUP BY F_得意先 ), ord_raw AS ( SELECT a.F_納入指定日 AS 日付, TRIM(a.F_区分) AS 計画区分, UPPER(TRIM(TO_SINGLE_BYTE(TRANSLATE(a.F_得意先, 'A'||CHR(9)||CHR(10)||CHR(13), 'A')))) AS 得意先番号, UPPER(TRIM(TO_SINGLE_BYTE(TRANSLATE(a.F_納入品目番号, 'A'||CHR(9)||CHR(10)||CHR(13), 'A')))) AS 品目コード, UPPER(TRIM(TO_SINGLE_BYTE(TRANSLATE(a.F_在庫品目番号, 'A'||CHR(9)||CHR(10)||CHR(13), 'A')))) AS 在庫品目コード, TRIM(a.F_納入品目番号) AS 単価品目, TRIM(a.F_得意先) AS 単価得意先, SUM(a.F_注文数) AS 数量 FROM PRONES.TB_統合注文情報 a CROSS JOIN rng JOIN PRONES.TB_得意先情報 c1 ON a.F_得意先 = c1.F_得意先番号 JOIN PRONES.TB_納入品目情報 i ON a.F_在庫品目番号 = i.F_納入品目番号 JOIN PRONES.TB_仕入先情報 s ON a.F_指示先 = s.F_仕入先番号 JOIN PRONES.TB_得意先情報 c2 ON a.F_納入先 = c2.F_得意先番号 WHERE SUBSTR(a.F_納入指定日,1,7) BETWEEN rng.実績開始 AND rng.出力終了 GROUP BY a.F_納入指定日, TRIM(a.F_区分), UPPER(TRIM(TO_SINGLE_BYTE(TRANSLATE(a.F_得意先, 'A'||CHR(9)||CHR(10)||CHR(13), 'A')))), UPPER(TRIM(TO_SINGLE_BYTE(TRANSLATE(a.F_納入品目番号, 'A'||CHR(9)||CHR(10)||CHR(13), 'A')))), UPPER(TRIM(TO_SINGLE_BYTE(TRANSLATE(a.F_在庫品目番号, 'A'||CHR(9)||CHR(10)||CHR(13), 'A')))), TRIM(a.F_納入品目番号), TRIM(a.F_得意先) ), ord AS ( SELECT 日付, 計画区分, 得意先番号, 品目コード, 在庫品目コード, 数量, 単価 FROM ( SELECT o.日付, o.計画区分, o.得意先番号, o.品目コード, o.在庫品目コード, o.数量, p.単価, ROW_NUMBER() OVER (PARTITION BY o.日付, o.計画区分, o.単価得意先, o.単価品目, o.在庫品目コード ORDER BY p.開始日 DESC) AS rn FROM ord_raw o LEFT JOIN px p ON p.品目 = o.単価品目 AND p.得意先 = o.単価得意先 AND p.開始日 <= o.日付 ) WHERE rn = 1 ), nai_raw AS ( SELECT d.F_納期 AS 日付, TRIM(d.F_区分) AS 計画区分, UPPER(TRIM(TO_SINGLE_BYTE(TRANSLATE(d.F_得意先, 'A'||CHR(9)||CHR(10)||CHR(13), 'A')))) AS 得意先番号, UPPER(TRIM(TO_SINGLE_BYTE(TRANSLATE(d.F_納入品目番号, 'A'||CHR(9)||CHR(10)||CHR(13), 'A')))) AS 品目コード, UPPER(TRIM(TO_SINGLE_BYTE(TRANSLATE(d.F_在庫品目番号, 'A'||CHR(9)||CHR(10)||CHR(13), 'A')))) AS 在庫品目コード, TRIM(d.F_在庫品目番号) AS 単価品目, TRIM(d.F_得意先) AS 単価得意先, SUM(d.F_数量 + d.F_調整数) AS 数量 FROM PRONES.TB_統合計画日別情報 d CROSS JOIN rng JOIN 内示最新作成日 l ON d.F_得意先 = l.F_得意先 AND d.F_作成日 = l.F_作成日 JOIN PRONES.TB_得意先情報 c ON d.F_得意先 = c.F_得意先番号 JOIN PRONES.TB_納入品目情報 i ON d.F_納入品目番号 = i.F_納入品目番号 JOIN PRONES.TB_仕入先情報 s ON d.F_指示先 = s.F_仕入先番号 WHERE SUBSTR(d.F_納期,1,7) >= rng.実績開始 GROUP BY d.F_納期, TRIM(d.F_区分), UPPER(TRIM(TO_SINGLE_BYTE(TRANSLATE(d.F_得意先, 'A'||CHR(9)||CHR(10)||CHR(13), 'A')))), UPPER(TRIM(TO_SINGLE_BYTE(TRANSLATE(d.F_納入品目番号, 'A'||CHR(9)||CHR(10)||CHR(13), 'A')))), UPPER(TRIM(TO_SINGLE_BYTE(TRANSLATE(d.F_在庫品目番号, 'A'||CHR(9)||CHR(10)||CHR(13), 'A')))), TRIM(d.F_在庫品目番号), TRIM(d.F_得意先) ), nai AS ( SELECT 日付, 計画区分, 得意先番号, 品目コード, 在庫品目コード, 数量, 単価 FROM ( SELECT n.日付, n.計画区分, n.得意先番号, n.品目コード, n.在庫品目コード, n.数量, p.単価, ROW_NUMBER() OVER (PARTITION BY n.日付, n.計画区分, n.単価得意先, n.単価品目, n.品目コード ORDER BY p.開始日 DESC) AS rn FROM nai_raw n JOIN px p ON p.品目 = n.単価品目 AND p.得意先 = n.単価得意先 AND p.開始日 <= n.日付 ) WHERE rn = 1 ), kakutei_m AS ( SELECT SUBSTR(日付,1,7) AS 年月, 得意先番号, SUM(数量 * 単価) AS 金額 FROM ord GROUP BY SUBSTR(日付,1,7), 得意先番号 ), naiji_m AS ( SELECT SUBSTR(日付,1,7) AS 年月, 得意先番号, SUM(数量 * 単価) AS 金額 FROM nai GROUP BY SUBSTR(日付,1,7), 得意先番号 ), lmax AS ( SELECT 得意先番号, TO_CHAR(ADD_MONTHS(TO_DATE(MAX(年月),'YYYY/MM'),-1),'YYYY/MM') AS 上限 FROM naiji_m WHERE 金額 > 0 GROUP BY 得意先番号 ), base3 AS ( SELECT TO_CHAR(ADD_MONTHS(TRUNC(SYSDATE,'MM'), -LEVEL),'YYYY/MM') AS 月 FROM DUAL CONNECT BY LEVEL <= 3 ), 実績3か月 AS ( SELECT 得意先番号, SUM(金額) AS 実績 FROM kakutei_m WHERE 年月 IN (SELECT 月 FROM base3) GROUP BY 得意先番号 ), 基期稼働日 AS (SELECT SUM(稼働日) AS d FROM cal WHERE 月 IN (SELECT 月 FROM base3)), 日次見込額 AS ( SELECT 得意先番号, 実績 / (SELECT d FROM 基期稼働日) AS 日次 FROM 実績3か月 ), 見込対象月 AS ( SELECT TO_CHAR(ADD_MONTHS(TRUNC(SYSDATE,'MM'), LEVEL),'YYYY/MM') AS 月 FROM DUAL CONNECT BY LEVEL <= 13 ), mikomi AS ( SELECT m.月 AS 年月, v.得意先番号, GREATEST(v.日次 * c.稼働日 - NVL(k.金額,0), 0) AS 金額 FROM 日次見込額 v CROSS JOIN 見込対象月 m JOIN cal c ON c.月 = m.月 LEFT JOIN lmax lx ON lx.得意先番号 = v.得意先番号 LEFT JOIN kakutei_m k ON k.得意先番号 = v.得意先番号 AND k.年月 = m.月 WHERE NOT (lx.上限 IS NOT NULL AND m.月 <= lx.上限) ) SELECT SUBSTR(o.日付,1,7) AS 年月, '確定' AS 区分種別, o.計画区分, o.得意先番号, o.得意先番号 || (chr(35)) || TO_CHAR(ORA_HASH(o.得意先番号)) AS 得意先キー, o.品目コード, o.在庫品目コード, SUM(o.数量) AS 数量, CASE WHEN SUM(o.数量) <> 0 THEN SUM(o.数量 * o.単価) / SUM(o.数量) END AS 単価, SUM(o.数量 * o.単価) AS 金額, TRUNC(SYSDATE) AS 基準日, CAST('通常' AS VARCHAR2(12)) AS 集計に含める FROM ord o CROSS JOIN rng WHERE SUBSTR(o.日付,1,7) BETWEEN rng.出力開始 AND rng.出力終了 GROUP BY SUBSTR(o.日付,1,7), o.計画区分, o.得意先番号, o.品目コード, o.在庫品目コード UNION ALL SELECT SUBSTR(n.日付,1,7), '内示', n.計画区分, n.得意先番号, n.得意先番号 || (chr(35)) || TO_CHAR(ORA_HASH(n.得意先番号)), n.品目コード, n.在庫品目コード, SUM(n.数量), CASE WHEN SUM(n.数量) <> 0 THEN SUM(n.数量 * n.単価) / SUM(n.数量) END, SUM(n.数量 * n.単価), TRUNC(SYSDATE), CAST(CASE WHEN n.得意先番号 = '1724601' THEN '住友の内示' ELSE '通常' END AS VARCHAR2(12)) FROM nai n CROSS JOIN rng JOIN lmax lx ON lx.得意先番号 = n.得意先番号 WHERE SUBSTR(n.日付,1,7) BETWEEN rng.出力開始 AND rng.出力終了 AND SUBSTR(n.日付,1,7) <= lx.上限 GROUP BY SUBSTR(n.日付,1,7), n.計画区分, n.得意先番号, n.品目コード, n.在庫品目コード UNION ALL SELECT mk.年月, '見込', CAST(NULL AS VARCHAR2(2)), mk.得意先番号, mk.得意先番号 || (chr(35)) || TO_CHAR(ORA_HASH(mk.得意先番号)), CAST(NULL AS VARCHAR2(30)), CAST(NULL AS VARCHAR2(30)), CAST(NULL AS NUMBER), CAST(NULL AS NUMBER), mk.金額, TRUNC(SYSDATE), CAST('通常' AS VARCHAR2(12)) FROM mikomi mk WHERE mk.金額 > 0 ) q"),
				    Source = Table.TransformColumnTypes(Raw, {{"年月", type text}, {"区分種別", type text}, {"計画区分", type text}, {"得意先番号", type text}, {"得意先キー", type text}, {"品目コード", type text}, {"在庫品目コード", type text}, {"数量", type number}, {"単価", type number}, {"金額", type number}, {"基準日", type date}, {"集計に含める", type text}})
				in
				    Source

	annotation PBI_ResultType = Table

