table Dim_Calendar
	lineageTag: 4f723305-0f52-425e-b349-9d9a7e8b440a

	column Year_Month
		dataType: string
		lineageTag: 26e5b866-1925-4c47-bd1d-f40c54a6dc99
		summarizeBy: none
		sourceColumn: YEAR_MONTH

		annotation SummarizationSetBy = Automatic

	column Month_Start
		dataType: dateTime
		formatString: yyyy/MM/dd
		lineageTag: 152d2e98-68db-405d-8123-f6b42fd4502a
		summarizeBy: none
		sourceColumn: MONTH_START

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		formatString: 0
		lineageTag: c2d98f3d-7e01-4961-883a-4f7bd1df691a
		summarizeBy: none
		sourceColumn: YEAR

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		formatString: 0
		lineageTag: 179c696d-0585-45b1-a7f0-16d46ee2380d
		summarizeBy: none
		sourceColumn: MONTH

		annotation SummarizationSetBy = Automatic

	column Year_Month_Label
		dataType: string
		lineageTag: ae6566a6-f2ca-4095-9e4f-28c42b5f8514
		summarizeBy: none
		sourceColumn: YEAR_MONTH_LABEL
		sortByColumn: Month_Start

		annotation SummarizationSetBy = Automatic

	partition Dim_Calendar = m
		mode: import
		source =
				let
				    Raw = Value.NativeQuery(Oracle.Database("(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=banshu-srv)(PORT=1521))(CONNECT_DATA=(SERVICE_NAME=prones)))"), "SELECT TO_CHAR(ADD_MONTHS(start_month, LEVEL-1),'YYYY/MM') AS Year_Month, ADD_MONTHS(start_month, LEVEL-1) AS Month_Start, TO_NUMBER(TO_CHAR(ADD_MONTHS(start_month, LEVEL-1),'YYYY')) AS Year, TO_NUMBER(TO_CHAR(ADD_MONTHS(start_month, LEVEL-1),'MM')) AS Month, TO_CHAR(ADD_MONTHS(start_month, LEVEL-1),'YYYY-MM') AS Year_Month_Label FROM (SELECT TRUNC(MIN(TO_DATE(F_売上日,'YYYY/MM/DD')),'MM') AS start_month, TRUNC(MAX(TO_DATE(F_売上日,'YYYY/MM/DD')),'MM') AS end_month FROM PRONES.TB_売上実績新情報 WHERE F_売上日 >= '2023/07/01') CONNECT BY LEVEL <= MONTHS_BETWEEN(end_month, start_month) + 1"),
				    Source = Table.TransformColumnTypes(Raw, {{"YEAR", Int64.Type}, {"MONTH", Int64.Type}, {"MONTH_START", type datetime}})
				in
				    Source

	annotation PBI_ResultType = Table

