table Dim_Customer
	lineageTag: 5cac79c7-d67d-4d5a-81b4-47a3bcb05347

	column Customer_No
		dataType: string
		lineageTag: 88aaaca8-bf74-4f9d-963a-8da1de8aa7b4
		summarizeBy: none
		sourceColumn: CUSTOMER_NO

		annotation SummarizationSetBy = Automatic

	column Customer_Key
		dataType: string
		lineageTag: a342b9f4-570a-4826-a329-81af9ef367c4
		summarizeBy: none
		sourceColumn: CUSTOMER_KEY

		annotation SummarizationSetBy = Automatic

	column Customer_Name
		dataType: string
		lineageTag: 3fa2bd35-07e0-45ae-a75d-14e90e36cdec
		summarizeBy: none
		sourceColumn: CUSTOMER_NAME

		annotation SummarizationSetBy = Automatic

	column Customer_Category
		dataType: string
		lineageTag: 83e6bb4b-204c-4657-9324-c1b9d1b5734f
		summarizeBy: none
		sourceColumn: Customer_Category
		sortByColumn: Customer_Category_Order

		annotation SummarizationSetBy = Automatic

	column Customer_Category_Order
		dataType: int64
		isHidden
		lineageTag: 6f2e1b3a-8c4d-4e5f-9a1b-2c3d4e5f6a7b
		summarizeBy: none
		sourceColumn: Customer_Category_Order

		annotation SummarizationSetBy = Automatic

	partition Dim_Customer = m
		mode: import
		source =
				let
				    CustomerRaw = Value.NativeQuery(Oracle.Database("(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=banshu-srv)(PORT=1521))(CONNECT_DATA=(SERVICE_NAME=prones)))"), "SELECT * FROM ( SELECT TRIM(F_得意先番号) AS Customer_No, TRIM(F_得意先番号) || (chr(35)) || TO_CHAR(ORA_HASH(TRIM(F_得意先番号))) AS Customer_Key, MAX(F_得意先略称) AS Customer_Name FROM PRONES.TB_得意先情報 GROUP BY TRIM(F_得意先番号) ) q"),
				    Mapping = Dim_Customer_Category_Map,
				    Merged = Table.NestedJoin(CustomerRaw, {"CUSTOMER_NO"}, Mapping, {"Customer_No"}, "MappingTable", JoinKind.LeftOuter),
				    Expanded = Table.ExpandTableColumn(Merged, "MappingTable", {"Customer_Category"}, {"Customer_Category_Raw"}),
				    Replaced = Table.ReplaceValue(Expanded, null, "Unclassified", Replacer.ReplaceValue, {"Customer_Category_Raw"}),
				    Renamed = Table.RenameColumns(Replaced, {{"Customer_Category_Raw", "Customer_Category"}}),
				    Source = Table.AddColumn(Renamed, "Customer_Category_Order", each
				        if [Customer_Category] = "Caterpillar Group" then 1
				        else if [Customer_Category] = "Kobelco Group" then 2
				        else if [Customer_Category] = "Komatsu Group" then 3
				        else if [Customer_Category] = "Other" then 4
				        else if [Customer_Category] = "Sumitomo Group" then 5
				        else if [Customer_Category] = "Hitachi Group" then 6
				        else if [Customer_Category] = "Intercompany" then 7
				        else if [Customer_Category] = "Inactive" then 8
				        else if [Customer_Category] = "Legacy Service" then 9
				        else 10, Int64.Type)
				in
				    Source

	annotation PBI_ResultType = Table

