table Fact_Sales
	lineageTag: 3fa4ad82-9ba5-4597-88eb-64b2ae08c26a

	measure Sales = SUM('Fact_Sales'[Amount])
		formatString: #,##0
		lineageTag: 6522abcf-36e7-4f08-a23f-e87dcb27e19b

	measure Sales_with_Actual_Price = CALCULATE(SUM('Fact_Sales'[Amount]), 'Fact_Sales'[Purchase_Price_Found] = "Yes")
		formatString: #,##0
		lineageTag: f5035337-a010-4031-9cc3-035d9d2e8d90

	measure Actual_Cost = CALCULATE(SUM('Fact_Sales'[Est_Actual_Cost]), 'Fact_Sales'[Purchase_Price_Found] = "Yes")
		formatString: #,##0
		lineageTag: ed855eff-e438-4aa4-ba42-a8152c5f4d4d

	measure Actual_Profit = [Sales_with_Actual_Price] - [Actual_Cost]
		formatString: #,##0
		lineageTag: a9637b56-ffae-4918-9ed2-f18f71c6ec30

	measure Actual_Profit_Rate = DIVIDE([Actual_Profit], [Sales_with_Actual_Price])
		formatString: 0.0%
		lineageTag: a7e068fc-95ce-402b-86a4-f59872a2c86b

	measure Actual_Price_Coverage = DIVIDE([Sales_with_Actual_Price], [Sales])
		formatString: 0.000%
		lineageTag: a9bfb256-b512-495c-ad63-18bb1e4ffb74

	measure Sales_with_Contract_Price = CALCULATE(SUM('Fact_Sales'[Amount]), 'Fact_Sales'[Contract_Price_Found] = "Yes")
		formatString: #,##0
		lineageTag: f464d093-a7cb-4262-a3ee-62852bdf4c1e

	measure Contract_Cost = CALCULATE(SUM('Fact_Sales'[Est_Contract_Cost]), 'Fact_Sales'[Contract_Price_Found] = "Yes")
		formatString: #,##0
		lineageTag: 2066f8e2-8f50-40a3-8e9d-4bcc087749b8

	measure Contract_Profit = [Sales_with_Contract_Price] - [Contract_Cost]
		formatString: #,##0
		lineageTag: 940c6725-2842-4f15-a817-3e23cff30412

	measure Contract_Profit_Rate = DIVIDE([Contract_Profit], [Sales_with_Contract_Price])
		formatString: 0.0%
		lineageTag: 06ee039d-8537-4325-81a4-17b8d9a77be1

	measure Contract_Price_Coverage = DIVIDE([Sales_with_Contract_Price], [Sales])
		formatString: 0.000%
		lineageTag: 3ff1e1b3-907a-43cd-98ef-4b625a4d488b

	measure Approx_Cost = SUM('Fact_Sales'[Est_Approx_Cost])
		formatString: #,##0
		lineageTag: 942e4dba-46f8-49e9-97f7-bf5d96e26ad3

	measure Approx_Profit = [Sales] - [Approx_Cost]
		formatString: #,##0
		lineageTag: 3c9b0fce-1404-479d-a536-0c84089c3502

	measure Approx_Profit_Rate = DIVIDE([Approx_Profit], [Sales])
		formatString: 0.0%
		lineageTag: 09859d42-330c-4520-9bd4-febbdffcce77

	measure Sales_YTD =
			VAR SelectedYear = SELECTEDVALUE('Dim_Calendar'[Year])
			VAR SelectedMonth = SELECTEDVALUE('Dim_Calendar'[Month])
			RETURN
			CALCULATE([Sales], FILTER(ALL('Dim_Calendar'), 'Dim_Calendar'[Year] = SelectedYear && 'Dim_Calendar'[Month] <= SelectedMonth))
		formatString: #,##0
		lineageTag: f7258e5b-e598-454d-802e-2c963bac9869

	measure Approx_Profit_YTD =
			VAR SelectedYear = SELECTEDVALUE('Dim_Calendar'[Year])
			VAR SelectedMonth = SELECTEDVALUE('Dim_Calendar'[Month])
			RETURN
			CALCULATE([Approx_Profit], FILTER(ALL('Dim_Calendar'), 'Dim_Calendar'[Year] = SelectedYear && 'Dim_Calendar'[Month] <= SelectedMonth))
		formatString: #,##0
		lineageTag: ed9b4d85-bf85-4dab-92ee-e00368c59dd0

	measure Approx_Profit_Rate_YTD = DIVIDE([Approx_Profit_YTD], [Sales_YTD])
		formatString: 0.0%
		lineageTag: 90b06a0f-e7fa-4675-82b9-ea7490879184

	measure Approx_Profit_Rate_PY_Same_Month =
			VAR SelectedYear = SELECTEDVALUE('Dim_Calendar'[Year])
			VAR SelectedMonth = SELECTEDVALUE('Dim_Calendar'[Month])
			RETURN
			CALCULATE([Approx_Profit_Rate], FILTER(ALL('Dim_Calendar'), 'Dim_Calendar'[Year] = SelectedYear - 1 && 'Dim_Calendar'[Month] = SelectedMonth))
		formatString: 0.0%
		lineageTag: 52247132-60be-4c97-99b7-72e799239723

	measure Approx_Profit_Rate_PY_Full_Year =
			VAR SelectedYear = SELECTEDVALUE('Dim_Calendar'[Year])
			RETURN
			CALCULATE([Approx_Profit_Rate], FILTER(ALL('Dim_Calendar'), 'Dim_Calendar'[Year] = SelectedYear - 1))
		formatString: 0.0%
		lineageTag: c5e0b09e-e917-49e7-9c26-5272c70466b9

	measure Approx_Profit_Rate_Change =
			VAR StartDate = CALCULATE(FIRSTNONBLANK('Dim_Calendar'[Month_Start], [Approx_Profit_Rate]), ALL('Dim_Calendar'[Year_Month_Label]))
			VAR EndDate = CALCULATE(LASTNONBLANK('Dim_Calendar'[Month_Start], [Approx_Profit_Rate]), ALL('Dim_Calendar'[Year_Month_Label]))
			VAR StartValue = CALCULATE([Approx_Profit_Rate], ALL('Dim_Calendar'[Year_Month_Label]), 'Dim_Calendar'[Month_Start] = StartDate)
			VAR EndValue = CALCULATE([Approx_Profit_Rate], ALL('Dim_Calendar'[Year_Month_Label]), 'Dim_Calendar'[Month_Start] = EndDate)
			RETURN
			EndValue - StartValue
		formatString: 0.0%
		lineageTag: 1a2b3c4d-5e6f-4708-9a0b-1c2d3e4f5061

	measure Approx_Profit_Rate_Change_Abs = ABS([Approx_Profit_Rate_Change])
		formatString: 0.0%
		lineageTag: b425d6e7-f809-4708-9405-162738495061

	measure Approx_Profit_Rate_Change_Rank = RANKX(ALL('Dim_Part'[Part_Code]), [Approx_Profit_Rate_Change_Abs])
		formatString: 0
		lineageTag: 2b3c4d5e-6f70-4819-0b1c-2d3e4f506172

	measure Actual_Profit_Rate_Change =
			VAR StartDate = CALCULATE(FIRSTNONBLANK('Dim_Calendar'[Month_Start], [Actual_Profit_Rate]), ALL('Dim_Calendar'[Year_Month_Label]))
			VAR EndDate = CALCULATE(LASTNONBLANK('Dim_Calendar'[Month_Start], [Actual_Profit_Rate]), ALL('Dim_Calendar'[Year_Month_Label]))
			VAR StartValue = CALCULATE([Actual_Profit_Rate], ALL('Dim_Calendar'[Year_Month_Label]), 'Dim_Calendar'[Month_Start] = StartDate)
			VAR EndValue = CALCULATE([Actual_Profit_Rate], ALL('Dim_Calendar'[Year_Month_Label]), 'Dim_Calendar'[Month_Start] = EndDate)
			RETURN
			EndValue - StartValue
		formatString: 0.0%
		lineageTag: 3c4d5e6f-7081-4920-1c2d-3e4f50617283

	measure Actual_Profit_Rate_Change_Abs = ABS([Actual_Profit_Rate_Change])
		formatString: 0.0%
		lineageTag: c536e7f8-091a-4819-0516-273849506172

	measure Actual_Profit_Rate_Change_Rank = RANKX(ALL('Dim_Part'[Part_Code]), [Actual_Profit_Rate_Change_Abs])
		formatString: 0
		lineageTag: 4d5e6f70-8192-4031-2d3e-4f5061728394

	measure Contract_Profit_Rate_Change =
			VAR StartDate = CALCULATE(FIRSTNONBLANK('Dim_Calendar'[Month_Start], [Contract_Profit_Rate]), ALL('Dim_Calendar'[Year_Month_Label]))
			VAR EndDate = CALCULATE(LASTNONBLANK('Dim_Calendar'[Month_Start], [Contract_Profit_Rate]), ALL('Dim_Calendar'[Year_Month_Label]))
			VAR StartValue = CALCULATE([Contract_Profit_Rate], ALL('Dim_Calendar'[Year_Month_Label]), 'Dim_Calendar'[Month_Start] = StartDate)
			VAR EndValue = CALCULATE([Contract_Profit_Rate], ALL('Dim_Calendar'[Year_Month_Label]), 'Dim_Calendar'[Month_Start] = EndDate)
			RETURN
			EndValue - StartValue
		formatString: 0.0%
		lineageTag: 5e6f7081-92a3-4142-3e4f-506172839405

	measure Contract_Profit_Rate_Change_Abs = ABS([Contract_Profit_Rate_Change])
		formatString: 0.0%
		lineageTag: d647f809-1a2b-4930-6273-849506172839

	measure Contract_Profit_Rate_Change_Rank = RANKX(ALL('Dim_Part'[Part_Code]), [Contract_Profit_Rate_Change_Abs])
		formatString: 0
		lineageTag: 6f708192-a3b4-4253-4f50-617283940516

	measure Sales_Change =
			VAR StartDate = CALCULATE(FIRSTNONBLANK('Dim_Calendar'[Month_Start], [Sales]), ALL('Dim_Calendar'[Year_Month_Label]))
			VAR EndDate = CALCULATE(LASTNONBLANK('Dim_Calendar'[Month_Start], [Sales]), ALL('Dim_Calendar'[Year_Month_Label]))
			VAR StartValue = CALCULATE([Sales], ALL('Dim_Calendar'[Year_Month_Label]), 'Dim_Calendar'[Month_Start] = StartDate)
			VAR EndValue = CALCULATE([Sales], ALL('Dim_Calendar'[Year_Month_Label]), 'Dim_Calendar'[Month_Start] = EndDate)
			RETURN
			EndValue - StartValue
		formatString: #,##0
		lineageTag: 708192a3-b4c5-4364-5061-728394051627

	measure Sales_Change_Abs = ABS([Sales_Change])
		formatString: #,##0
		lineageTag: e758f901-2b3c-4041-7384-950617283940

	measure Sales_Change_Rank = RANKX(ALL('Dim_Part'[Part_Code]), [Sales_Change_Abs])
		formatString: 0
		lineageTag: 8192a3b4-c5d6-4475-6172-839405162738

	column Customer_No
		dataType: string
		lineageTag: 09726bea-bdbe-4295-8dc9-c60319d05689
		summarizeBy: none
		sourceColumn: CUSTOMER_NO

		annotation SummarizationSetBy = Automatic

	column Customer_Key
		dataType: string
		lineageTag: e35a868f-54d1-4865-b0f0-ceed16a29075
		summarizeBy: none
		sourceColumn: CUSTOMER_KEY

		annotation SummarizationSetBy = Automatic

	column Part_Code
		dataType: string
		lineageTag: 8278c140-4424-479a-9078-fabbb41a8717
		summarizeBy: none
		sourceColumn: PART_CODE

		annotation SummarizationSetBy = Automatic

	column Year_Month
		dataType: string
		lineageTag: 391e50e0-5b37-462d-ba44-5785feccd04c
		summarizeBy: none
		sourceColumn: YEAR_MONTH

		annotation SummarizationSetBy = Automatic

	column Qty
		dataType: double
		formatString: #,##0
		lineageTag: de9e7c09-4c27-480f-bca5-b27da7e02981
		summarizeBy: sum
		sourceColumn: QTY

		annotation SummarizationSetBy = Automatic

	column Amount
		dataType: double
		formatString: #,##0
		lineageTag: 2b52cda0-7f42-4214-8c04-6c6d49e9bc0d
		summarizeBy: sum
		sourceColumn: AMOUNT

		annotation SummarizationSetBy = Automatic

	column Purchase_Unit_Price
		dataType: double
		formatString: #,##0.00
		lineageTag: d91a99f3-eb8c-4d82-b818-264b49c0507b
		summarizeBy: none
		sourceColumn: PURCHASE_UNIT_PRICE

		annotation SummarizationSetBy = Automatic

	column Est_Actual_Cost
		dataType: double
		formatString: #,##0
		lineageTag: 8b628d57-f1c0-4b68-805c-b0a79b653c36
		summarizeBy: sum
		sourceColumn: EST_ACTUAL_COST

		annotation SummarizationSetBy = Automatic

	column Purchase_Year_Month
		dataType: string
		lineageTag: 5e1d9856-1315-47db-830b-5ab48e182180
		summarizeBy: none
		sourceColumn: PURCHASE_YEAR_MONTH

		annotation SummarizationSetBy = Automatic

	column Costing_Method
		dataType: string
		lineageTag: e956c23c-ef9f-4d25-954c-0e63c12f4733
		summarizeBy: none
		sourceColumn: COSTING_METHOD

		annotation SummarizationSetBy = Automatic

	column Max_Unit_Price
		dataType: double
		formatString: #,##0.00
		lineageTag: 4a8731b9-29b3-41b6-b259-4996762d4702
		summarizeBy: none
		sourceColumn: MAX_UNIT_PRICE

		annotation SummarizationSetBy = Automatic

	column Min_Unit_Price
		dataType: double
		formatString: #,##0.00
		lineageTag: 5ca32a14-7f94-4ba6-b228-7cd1ee7fe641
		summarizeBy: none
		sourceColumn: MIN_UNIT_PRICE

		annotation SummarizationSetBy = Automatic

	column Avg_Unit_Price
		dataType: double
		formatString: #,##0.00
		lineageTag: b1e1607a-1e29-4ced-9b01-2760bf7347f0
		summarizeBy: none
		sourceColumn: AVG_UNIT_PRICE

		annotation SummarizationSetBy = Automatic

	column Contract_Unit_Price
		dataType: double
		formatString: #,##0.00
		lineageTag: 5c299f36-36c8-42f8-87db-a4fb2b455426
		summarizeBy: none
		sourceColumn: CONTRACT_UNIT_PRICE

		annotation SummarizationSetBy = Automatic

	column Est_Contract_Cost
		dataType: double
		formatString: #,##0
		lineageTag: 7d4ee962-ce96-441a-a53c-2ffda8535c99
		summarizeBy: sum
		sourceColumn: EST_CONTRACT_COST

		annotation SummarizationSetBy = Automatic

	column Supplier_Category
		dataType: string
		lineageTag: ea3ee99e-6e29-4e2e-ac65-a3ebab4b0e7e
		summarizeBy: none
		sourceColumn: SUPPLIER_CATEGORY

		annotation SummarizationSetBy = Automatic

	column Supplier_Name
		dataType: string
		lineageTag: e9eabfb4-825b-4f39-a08c-f1baa6692dfc
		summarizeBy: none
		sourceColumn: SUPPLIER_NAME

		annotation SummarizationSetBy = Automatic

	column Purchase_Price_Found
		dataType: string
		lineageTag: 2aaeb2c1-79a2-4783-8919-187542cf7eda
		summarizeBy: none
		sourceColumn: PURCHASE_PRICE_FOUND

		annotation SummarizationSetBy = Automatic

	column Contract_Price_Found
		dataType: string
		lineageTag: fbc8cd75-e48f-4efc-a235-df035230d498
		summarizeBy: none
		sourceColumn: CONTRACT_PRICE_FOUND

		annotation SummarizationSetBy = Automatic

	column Est_Approx_Cost
		dataType: double
		formatString: #,##0
		lineageTag: 771cabc3-1837-4104-a6f8-5257bf109976
		summarizeBy: sum
		sourceColumn: EST_APPROX_COST

		annotation SummarizationSetBy = Automatic

	column Approx_Cost_Method
		dataType: string
		lineageTag: f3a7a9db-a52d-4454-9fd9-f7c133f81910
		summarizeBy: none
		sourceColumn: APPROX_COST_METHOD

		annotation SummarizationSetBy = Automatic

	column Last_Updated
		dataType: dateTime
		formatString: yyyy/MM/dd
		lineageTag: c827eb75-81ae-44dc-a271-144971278dab
		summarizeBy: none
		sourceColumn: LAST_UPDATED

		annotation SummarizationSetBy = Automatic

	column Sales_Date
		dataType: dateTime
		formatString: yyyy/MM/dd
		lineageTag: 9182b153-7fc8-4750-925b-7af470ad0f7e
		summarizeBy: none
		sourceColumn: SALES_DATE

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Contract_Price_Eff_Date
		dataType: dateTime
		formatString: yyyy/MM/dd
		lineageTag: 4b3a288b-169f-48f9-b541-8cfe9e5ac1f4
		summarizeBy: none
		sourceColumn: CONTRACT_PRICE_EFF_DATE

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Customer_Category = RELATED('Dim_Customer'[Customer_Category])
		dataType: string
		lineageTag: ce89ab7d-ad56-44d2-9a6b-c3885916d4ec
		summarizeBy: none
		sortByColumn: Customer_Category_Order

		annotation SummarizationSetBy = Automatic

	column Customer_Category_Order = RELATED('Dim_Customer'[Customer_Category_Order])
		dataType: int64
		isHidden
		lineageTag: 4de49370-23b2-4e98-b6ce-2bb45c328133
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Sales_Unit_Price = DIVIDE('Fact_Sales'[Amount], 'Fact_Sales'[Qty])
		dataType: double
		formatString: #,##0.00
		lineageTag: 6f3a1c8e-2b47-4d9a-8e5c-1a9f6d3b2c7e
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition Fact_Sales = m
		mode: import
		source =
				let
				    Raw = Value.NativeQuery(Oracle.Database("(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=banshu-srv)(PORT=1521))(CONNECT_DATA=(SERVICE_NAME=prones)))"), "SELECT * FROM ( WITH items AS (SELECT DISTINCT TRIM(F_在庫品目番号) AS Part_Code FROM PRONES.TB_売上実績新情報 WHERE F_売上日 >= '2023/07/01'), months AS (SELECT TO_CHAR(ADD_MONTHS(DATE '2017-01-01', LEVEL-1),'YYYY/MM') AS Year_Month, ADD_MONTHS(DATE '2017-01-01', LEVEL-1) AS Year_Month_Date FROM DUAL CONNECT BY LEVEL <= 115), grid AS (SELECT i.Part_Code, m.Year_Month, m.Year_Month_Date FROM items i CROSS JOIN months m), purchase_monthly AS (SELECT TRIM(F_品目番号) AS Part_Code, F_勘定年月 AS Year_Month, TO_DATE(F_勘定年月,'YYYY/MM') AS Year_Month_Date, SUM(F_仕入数) AS Purchase_Qty, SUM(F_金額) AS Purchase_Amount, CASE WHEN SUM(F_仕入数)<>0 THEN SUM(F_金額)/SUM(F_仕入数) END AS Month_Unit_Price, MAX(CASE WHEN F_仕入数<>0 THEN F_金額/F_仕入数 END) AS Month_Max_Unit_Price, MIN(CASE WHEN F_仕入数<>0 THEN F_金額/F_仕入数 END) AS Month_Min_Unit_Price, AVG(CASE WHEN F_仕入数<>0 THEN F_金額/F_仕入数 END) AS Month_Simple_Avg_Unit_Price FROM PRONES.TB_仕入実績情報 GROUP BY TRIM(F_品目番号), F_勘定年月), windowed AS (SELECT g.Part_Code, g.Year_Month, CASE WHEN SUM(pm.Purchase_Qty) IS NOT NULL AND SUM(pm.Purchase_Qty)<>0 THEN SUM(pm.Purchase_Amount)/SUM(pm.Purchase_Qty) END AS Eff_Purchase_Unit_Price_6mo, MAX(pm.Month_Unit_Price) AS Window_Max_Unit_Price, MIN(pm.Month_Unit_Price) AS Window_Min_Unit_Price FROM grid g LEFT JOIN purchase_monthly pm ON pm.Part_Code = g.Part_Code AND pm.Year_Month_Date BETWEEN ADD_MONTHS(g.Year_Month_Date,-5) AND g.Year_Month_Date GROUP BY g.Part_Code, g.Year_Month), carried AS (SELECT g.Part_Code, g.Year_Month, LAST_VALUE(pm.Month_Unit_Price IGNORE NULLS) OVER (PARTITION BY g.Part_Code ORDER BY g.Year_Month_Date) AS Eff_Purchase_Unit_Price_Carry, LAST_VALUE(CASE WHEN pm.Month_Unit_Price IS NOT NULL THEN pm.Year_Month END IGNORE NULLS) OVER (PARTITION BY g.Part_Code ORDER BY g.Year_Month_Date) AS Carry_Purchase_Year_Month, LAST_VALUE(pm.Month_Max_Unit_Price IGNORE NULLS) OVER (PARTITION BY g.Part_Code ORDER BY g.Year_Month_Date) AS Carry_Max_Unit_Price, LAST_VALUE(pm.Month_Min_Unit_Price IGNORE NULLS) OVER (PARTITION BY g.Part_Code ORDER BY g.Year_Month_Date) AS Carry_Min_Unit_Price, LAST_VALUE(pm.Month_Simple_Avg_Unit_Price IGNORE NULLS) OVER (PARTITION BY g.Part_Code ORDER BY g.Year_Month_Date) AS Carry_Avg_Unit_Price FROM grid g LEFT JOIN purchase_monthly pm ON pm.Part_Code = g.Part_Code AND pm.Year_Month_Date = g.Year_Month_Date), purchase_by_supplier AS (SELECT TRIM(F_品目番号) AS Part_Code, F_勘定年月 AS Year_Month, TO_DATE(F_勘定年月,'YYYY/MM') AS Year_Month_Date, TRIM(F_指示先番号) AS Supplier_No, SUM(F_金額) AS Amount FROM PRONES.TB_仕入実績情報 GROUP BY TRIM(F_品目番号), F_勘定年月, TRIM(F_指示先番号)), supplier_name AS (SELECT TRIM(F_仕入先番号) AS Supplier_No, MAX(F_仕入先略称) AS Supplier_Name FROM PRONES.TB_仕入先情報 GROUP BY TRIM(F_仕入先番号)), windowed_sup AS (SELECT g.Part_Code, g.Year_Month, COUNT(DISTINCT pbs.Supplier_No) AS Cnt, MAX(pbs.Supplier_No) AS Single_Supplier FROM grid g LEFT JOIN purchase_by_supplier pbs ON pbs.Part_Code = g.Part_Code AND pbs.Year_Month_Date BETWEEN ADD_MONTHS(g.Year_Month_Date,-5) AND g.Year_Month_Date GROUP BY g.Part_Code, g.Year_Month), carried_sup AS (SELECT c.Part_Code, c.Year_Month, COUNT(DISTINCT pbs.Supplier_No) AS Cnt, MAX(pbs.Supplier_No) AS Single_Supplier FROM carried c LEFT JOIN purchase_by_supplier pbs ON pbs.Part_Code = c.Part_Code AND pbs.Year_Month = c.Carry_Purchase_Year_Month GROUP BY c.Part_Code, c.Year_Month), final_price AS (SELECT w.Part_Code, w.Year_Month, COALESCE(w.Eff_Purchase_Unit_Price_6mo, c.Eff_Purchase_Unit_Price_Carry) AS Eff_Purchase_Unit_Price, CASE WHEN w.Eff_Purchase_Unit_Price_6mo IS NOT NULL THEN w.Year_Month ELSE c.Carry_Purchase_Year_Month END AS Purchase_Year_Month, CASE WHEN w.Eff_Purchase_Unit_Price_6mo IS NOT NULL THEN w.Window_Max_Unit_Price ELSE c.Carry_Max_Unit_Price END AS Max_Unit_Price, CASE WHEN w.Eff_Purchase_Unit_Price_6mo IS NOT NULL THEN w.Window_Min_Unit_Price ELSE c.Carry_Min_Unit_Price END AS Min_Unit_Price, CASE WHEN w.Eff_Purchase_Unit_Price_6mo IS NOT NULL THEN w.Eff_Purchase_Unit_Price_6mo ELSE c.Carry_Avg_Unit_Price END AS Avg_Unit_Price, CASE WHEN w.Eff_Purchase_Unit_Price_6mo IS NOT NULL THEN '6-Month Avg' WHEN c.Eff_Purchase_Unit_Price_Carry IS NOT NULL THEN 'Single Month' END AS Costing_Method, CASE WHEN w.Eff_Purchase_Unit_Price_6mo IS NOT NULL THEN CASE WHEN ws.Cnt = 1 THEN snw.Supplier_Name WHEN ws.Cnt > 1 THEN '*' END ELSE CASE WHEN cs.Cnt = 1 THEN snc.Supplier_Name WHEN cs.Cnt > 1 THEN '*' END END AS Supplier_Name_Src FROM windowed w JOIN carried c ON c.Part_Code = w.Part_Code AND c.Year_Month = w.Year_Month LEFT JOIN windowed_sup ws ON ws.Part_Code = w.Part_Code AND ws.Year_Month = w.Year_Month LEFT JOIN carried_sup cs ON cs.Part_Code = w.Part_Code AND cs.Year_Month = w.Year_Month LEFT JOIN supplier_name snw ON snw.Supplier_No = ws.Single_Supplier LEFT JOIN supplier_name snc ON snc.Supplier_No = cs.Single_Supplier), sale_days AS (SELECT DISTINCT TRIM(F_在庫品目番号) AS Part_Code, F_売上日 FROM PRONES.TB_売上実績新情報 WHERE F_売上日 >= '2023/07/01'), item_designated_supplier AS (SELECT TRIM(F_納入品目番号) AS Part_Code, MAX(TRIM(F_指示先番号)) AS Designated_Supplier FROM PRONES.TB_納入品目情報 GROUP BY TRIM(F_納入品目番号)), contract_price AS (SELECT TRIM(F_納入品目番号) AS Part_Code, TRIM(F_仕入先番号) AS Supplier, F_契約単価, CASE WHEN TRANSLATE(F_開始日,'0123456789','9999999999') = '9999/99/99' THEN TO_DATE(F_開始日,'YYYY/MM/DD') END AS Start_Date FROM PRONES.TB_納入品目仕入先単価情報 WHERE F_契約単価 > 0), contract_ranked AS (SELECT sd.Part_Code, sd.F_売上日, cp.F_契約単価, cp.Start_Date, ROW_NUMBER() OVER (PARTITION BY sd.Part_Code, sd.F_売上日 ORDER BY CASE WHEN cp.Supplier = ids.Designated_Supplier THEN 0 ELSE 1 END, cp.Start_Date DESC) AS rn FROM sale_days sd LEFT JOIN item_designated_supplier ids ON ids.Part_Code = sd.Part_Code JOIN contract_price cp ON cp.Part_Code = sd.Part_Code AND cp.Start_Date IS NOT NULL AND cp.Start_Date <= TO_DATE(sd.F_売上日,'YYYY/MM/DD')), contract_effective AS (SELECT Part_Code, F_売上日, F_契約単価 AS Contract_Unit_Price, Start_Date FROM contract_ranked WHERE rn = 1), primary_supplier AS (SELECT Part_Code, Supplier_No FROM (SELECT TRIM(F_品目番号) AS Part_Code, TRIM(F_指示先番号) AS Supplier_No, SUM(F_金額) AS Amount, ROW_NUMBER() OVER (PARTITION BY TRIM(F_品目番号) ORDER BY SUM(F_金額) DESC) AS rn FROM PRONES.TB_仕入実績情報 WHERE F_勘定年月 >= '2017/01' GROUP BY TRIM(F_品目番号), TRIM(F_指示先番号)) WHERE rn = 1) SELECT TRIM(s.F_得意先番号) AS Customer_No, MAX(TRIM(s.F_得意先番号) || (chr(35)) || TO_CHAR(ORA_HASH(TRIM(s.F_得意先番号)))) AS Customer_Key, TRIM(s.F_在庫品目番号) AS Part_Code, SUBSTR(s.F_売上日,1,7) AS Year_Month, TO_DATE(s.F_売上日,'YYYY/MM/DD') AS Sales_Date, SUM(s.F_数量) AS Qty, SUM(s.F_金額) AS Amount, MAX(fp.Eff_Purchase_Unit_Price) AS Purchase_Unit_Price, ROUND(SUM(s.F_数量) * MAX(fp.Eff_Purchase_Unit_Price)) AS Est_Actual_Cost, CASE WHEN MAX(fp.Eff_Purchase_Unit_Price) IS NOT NULL THEN 'Yes' ELSE 'No' END AS Purchase_Price_Found, MAX(fp.Purchase_Year_Month) AS Purchase_Year_Month, MAX(fp.Supplier_Name_Src) AS Supplier_Name, MAX(fp.Costing_Method) AS Costing_Method, MAX(fp.Max_Unit_Price) AS Max_Unit_Price, MAX(fp.Min_Unit_Price) AS Min_Unit_Price, MAX(fp.Avg_Unit_Price) AS Avg_Unit_Price, MAX(ce.Contract_Unit_Price) AS Contract_Unit_Price, MAX(ce.Start_Date) AS Contract_Price_Eff_Date, ROUND(SUM(s.F_数量) * MAX(ce.Contract_Unit_Price)) AS Est_Contract_Cost, CASE WHEN MAX(ce.Contract_Unit_Price) IS NOT NULL THEN 'Yes' ELSE 'No' END AS Contract_Price_Found, CASE WHEN MAX(ps.Supplier_No) IS NULL THEN 'No Purchase Record' WHEN MAX(ps.Supplier_No) IN ('2000001','2000002','2000004','2000005','2000006','2000007') THEN 'BEI' ELSE 'Other' END AS Supplier_Category, CASE WHEN MAX(ce.Contract_Unit_Price) IS NOT NULL THEN ROUND(SUM(s.F_数量) * MAX(ce.Contract_Unit_Price)) ELSE ROUND(SUM(s.F_金額) * 0.85) END AS Est_Approx_Cost, CASE WHEN MAX(ce.Contract_Unit_Price) IS NOT NULL THEN 'Contract Price' ELSE 'Sales x 85%' END AS Approx_Cost_Method, MAX(s.F_登録日) AS Last_Updated FROM PRONES.TB_売上実績新情報 s LEFT JOIN final_price fp ON fp.Part_Code = TRIM(s.F_在庫品目番号) AND fp.Year_Month = SUBSTR(s.F_売上日,1,7) LEFT JOIN contract_effective ce ON ce.Part_Code = TRIM(s.F_在庫品目番号) AND ce.F_売上日 = s.F_売上日 LEFT JOIN primary_supplier ps ON ps.Part_Code = TRIM(s.F_在庫品目番号) WHERE s.F_売上日 >= '2023/07/01' GROUP BY TRIM(s.F_得意先番号), TRIM(s.F_在庫品目番号), s.F_売上日 ) q"),
				    Source = Table.TransformColumnTypes(Raw, {{"PURCHASE_PRICE_FOUND", type text}, {"SALES_DATE", type date}, {"QTY", type number}, {"AMOUNT", type number}, {"PURCHASE_UNIT_PRICE", type number}, {"EST_ACTUAL_COST", type number}, {"PURCHASE_YEAR_MONTH", type text}, {"SUPPLIER_NAME", type text}, {"COSTING_METHOD", type text}, {"MAX_UNIT_PRICE", type number}, {"MIN_UNIT_PRICE", type number}, {"AVG_UNIT_PRICE", type number}, {"CONTRACT_UNIT_PRICE", type number}, {"CONTRACT_PRICE_EFF_DATE", type date}, {"EST_CONTRACT_COST", type number}, {"CONTRACT_PRICE_FOUND", type text}, {"SUPPLIER_CATEGORY", type text}, {"EST_APPROX_COST", type number}, {"APPROX_COST_METHOD", type text}, {"LAST_UPDATED", type datetime}})
				in
				    Source

	annotation PBI_ResultType = Table

