table Fact_Purchase
	lineageTag: 20ae447d-98e9-411a-a9bb-26c563e881bb

	column Part_Code
		dataType: string
		lineageTag: 12f79275-8740-4198-a8e6-631e029289a1
		summarizeBy: none
		sourceColumn: PART_CODE

		annotation SummarizationSetBy = Automatic

	column Year_Month
		dataType: string
		lineageTag: cca636c5-e4fb-42a7-8c80-bf0c8d547e24
		summarizeBy: none
		sourceColumn: YEAR_MONTH

		annotation SummarizationSetBy = Automatic

	column Purchase_Qty
		dataType: double
		formatString: #,##0
		lineageTag: 4b0eeec0-cc51-4b72-bfa6-064a724d5ad0
		summarizeBy: sum
		sourceColumn: PURCHASE_QTY

		annotation SummarizationSetBy = Automatic

	column Purchase_Amount
		dataType: double
		formatString: #,##0
		lineageTag: bbcdf8ab-d93e-4859-8af3-17c392296de9
		summarizeBy: sum
		sourceColumn: PURCHASE_AMOUNT

		annotation SummarizationSetBy = Automatic

	column Avg_Purchase_Unit_Price
		dataType: double
		formatString: #,##0.00
		lineageTag: fe81692e-1f26-43a0-ab66-4e1938c9c8f6
		summarizeBy: none
		sourceColumn: AVG_PURCHASE_UNIT_PRICE

		annotation SummarizationSetBy = Automatic

	column Supplier_No
		dataType: string
		lineageTag: 18eb6002-278f-4521-911b-74932a58e4e2
		summarizeBy: none
		sourceColumn: SUPPLIER_NO

		annotation SummarizationSetBy = Automatic

	partition Fact_Purchase = m
		mode: import
		source =
				let
				    Raw = Value.NativeQuery(Oracle.Database("(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=banshu-srv)(PORT=1521))(CONNECT_DATA=(SERVICE_NAME=prones)))"), "SELECT * FROM ( WITH monthly_totals AS (SELECT TRIM(F_品目番号) AS Part_Code, F_勘定年月 AS Year_Month, SUM(F_仕入数) AS Purchase_Qty, SUM(F_金額) AS Purchase_Amount FROM PRONES.TB_仕入実績情報 WHERE TRIM(F_品目番号) NOT IN ('99999','N-99999') GROUP BY TRIM(F_品目番号), F_勘定年月), top_supplier AS (SELECT Part_Code, Year_Month, Supplier_No FROM (SELECT TRIM(F_品目番号) AS Part_Code, F_勘定年月 AS Year_Month, TRIM(F_指示先番号) AS Supplier_No, SUM(F_金額) AS Amount, ROW_NUMBER() OVER (PARTITION BY TRIM(F_品目番号), F_勘定年月 ORDER BY SUM(F_金額) DESC) AS rn FROM PRONES.TB_仕入実績情報 WHERE TRIM(F_品目番号) NOT IN ('99999','N-99999') GROUP BY TRIM(F_品目番号), F_勘定年月, TRIM(F_指示先番号)) WHERE rn = 1) SELECT mt.Part_Code, mt.Year_Month, mt.Purchase_Qty, mt.Purchase_Amount, ROUND(mt.Purchase_Amount/NULLIF(mt.Purchase_Qty,0),2) AS Avg_Purchase_Unit_Price, ts.Supplier_No FROM monthly_totals mt LEFT JOIN top_supplier ts ON ts.Part_Code = mt.Part_Code AND ts.Year_Month = mt.Year_Month ) q"),
				    Source = Table.TransformColumnTypes(Raw, {{"PURCHASE_QTY", type number}, {"PURCHASE_AMOUNT", type number}, {"AVG_PURCHASE_UNIT_PRICE", type number}})
				in
				    Source

	annotation PBI_ResultType = Table

