table Dim_得意先
	lineageTag: 5cac79c7-d67d-4d5a-81b4-47a3bcb05347

	column 得意先番号
		dataType: string
		lineageTag: 88aaaca8-bf74-4f9d-963a-8da1de8aa7b4
		summarizeBy: none
		sourceColumn: 得意先番号

		annotation SummarizationSetBy = Automatic

	column 得意先キー
		dataType: string
		lineageTag: a342b9f4-570a-4826-a329-81af9ef367c4
		summarizeBy: none
		sourceColumn: 得意先キー

		annotation SummarizationSetBy = Automatic

	column 得意先略称
		dataType: string
		lineageTag: 3fa2bd35-07e0-45ae-a75d-14e90e36cdec
		summarizeBy: none
		sourceColumn: 得意先略称

		annotation SummarizationSetBy = Automatic

	column 得意先区分
		dataType: string
		lineageTag: 83e6bb4b-204c-4657-9324-c1b9d1b5734f
		summarizeBy: none
		sourceColumn: 得意先区分
		sortByColumn: 得意先区分順序

		annotation SummarizationSetBy = Automatic

	column 得意先区分順序
		dataType: int64
		isHidden
		lineageTag: 6f2e1b3a-8c4d-4e5f-9a1b-2c3d4e5f6a7b
		summarizeBy: none
		sourceColumn: 得意先区分順序

		annotation SummarizationSetBy = Automatic

	partition Dim_得意先 = m
		mode: import
		source =
				let
				    CustomerRaw = Value.NativeQuery(Oracle.Database("(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=banshu-srv)(PORT=1521))(CONNECT_DATA=(SERVICE_NAME=prones)))"), "SELECT * FROM ( SELECT TRIM(F_得意先番号) AS 得意先番号, TRIM(F_得意先番号) || (chr(35)) || TO_CHAR(ORA_HASH(TRIM(F_得意先番号))) AS 得意先キー, MAX(F_得意先略称) AS 得意先略称 FROM PRONES.TB_得意先情報 GROUP BY TRIM(F_得意先番号) ) q"),
				    Mapping = Dim_得意先区分マッピング,
				    Merged = Table.NestedJoin(CustomerRaw, {"得意先番号"}, Mapping, {"得意先番号"}, "MappingTable", JoinKind.LeftOuter),
				    Expanded = Table.ExpandTableColumn(Merged, "MappingTable", {"得意先区分"}, {"得意先区分_raw"}),
				    Replaced = Table.ReplaceValue(Expanded, null, "未分類", Replacer.ReplaceValue, {"得意先区分_raw"}),
				    Renamed = Table.RenameColumns(Replaced, {{"得意先区分_raw", "得意先区分"}}),
				    Source = Table.AddColumn(Renamed, "得意先区分順序", each
				        if [得意先区分] = "キャタピラー系" then 1
				        else if [得意先区分] = "コベルコ系" then 2
				        else if [得意先区分] = "コマツ系" then 3
				        else if [得意先区分] = "その他" then 4
				        else if [得意先区分] = "住友系" then 5
				        else if [得意先区分] = "日立系" then 6
				        else if [得意先区分] = "社内売り" then 7
				        else if [得意先区分] = "現在売上なし" then 8
				        else if [得意先区分] = "旧サービス" then 9
				        else 10, Int64.Type)
				in
				    Source

	annotation PBI_ResultType = Table

