table Fact_売上実績
	lineageTag: 3fa4ad82-9ba5-4597-88eb-64b2ae08c26a

	measure 売上高 = SUM('Fact_売上実績'[金額])
		formatString: #,##0
		lineageTag: 6522abcf-36e7-4f08-a23f-e87dcb27e19b

	measure 仕入単価あり売上高 = CALCULATE(SUM('Fact_売上実績'[金額]), 'Fact_売上実績'[仕入単価有無] = "あり")
		formatString: #,##0
		lineageTag: f5035337-a010-4031-9cc3-035d9d2e8d90

	measure 仕入原価 = CALCULATE(SUM('Fact_売上実績'[仕入原価推定]), 'Fact_売上実績'[仕入単価有無] = "あり")
		formatString: #,##0
		lineageTag: ed855eff-e438-4aa4-ba42-a8152c5f4d4d

	measure 利益 = [仕入単価あり売上高] - [仕入原価]
		formatString: #,##0
		lineageTag: a9637b56-ffae-4918-9ed2-f18f71c6ec30

	measure 利益率 = DIVIDE([利益], [仕入単価あり売上高])
		formatString: 0.0%
		lineageTag: a7e068fc-95ce-402b-86a4-f59872a2c86b

	measure 仕入単価取得率 = DIVIDE([仕入単価あり売上高], [売上高])
		formatString: 0.000%
		lineageTag: a9bfb256-b512-495c-ad63-18bb1e4ffb74

	measure 仕入契約単価あり売上高 = CALCULATE(SUM('Fact_売上実績'[金額]), 'Fact_売上実績'[仕入契約単価有無] = "あり")
		formatString: #,##0
		lineageTag: f464d093-a7cb-4262-a3ee-62852bdf4c1e

	measure 契約仕入原価 = CALCULATE(SUM('Fact_売上実績'[契約仕入原価推定]), 'Fact_売上実績'[仕入契約単価有無] = "あり")
		formatString: #,##0
		lineageTag: 2066f8e2-8f50-40a3-8e9d-4bcc087749b8

	measure 契約利益 = [仕入契約単価あり売上高] - [契約仕入原価]
		formatString: #,##0
		lineageTag: 940c6725-2842-4f15-a817-3e23cff30412

	measure 契約利益率 = DIVIDE([契約利益], [仕入契約単価あり売上高])
		formatString: 0.0%
		lineageTag: 06ee039d-8537-4325-81a4-17b8d9a77be1

	measure 仕入契約単価取得率 = DIVIDE([仕入契約単価あり売上高], [売上高])
		formatString: 0.000%
		lineageTag: 3ff1e1b3-907a-43cd-98ef-4b625a4d488b

	measure 概算仕入原価 = SUM('Fact_売上実績'[概算仕入原価推定])
		formatString: #,##0
		lineageTag: 942e4dba-46f8-49e9-97f7-bf5d96e26ad3

	measure 概算利益 = [売上高] - [概算仕入原価]
		formatString: #,##0
		lineageTag: 3c9b0fce-1404-479d-a536-0c84089c3502

	measure 概算利益率 = DIVIDE([概算利益], [売上高])
		formatString: 0.0%
		lineageTag: 09859d42-330c-4520-9bd4-febbdffcce77

	column 得意先番号
		dataType: string
		lineageTag: 09726bea-bdbe-4295-8dc9-c60319d05689
		summarizeBy: none
		sourceColumn: 得意先番号

		annotation SummarizationSetBy = Automatic

	column 得意先キー
		dataType: string
		lineageTag: e35a868f-54d1-4865-b0f0-ceed16a29075
		summarizeBy: none
		sourceColumn: 得意先キー

		annotation SummarizationSetBy = Automatic

	column 品目コード
		dataType: string
		lineageTag: 8278c140-4424-479a-9078-fabbb41a8717
		summarizeBy: none
		sourceColumn: 品目コード

		annotation SummarizationSetBy = Automatic

	column 年月
		dataType: string
		lineageTag: 391e50e0-5b37-462d-ba44-5785feccd04c
		summarizeBy: none
		sourceColumn: 年月

		annotation SummarizationSetBy = Automatic

	column 数量
		dataType: double
		formatString: #,##0
		lineageTag: de9e7c09-4c27-480f-bca5-b27da7e02981
		summarizeBy: sum
		sourceColumn: 数量

		annotation SummarizationSetBy = Automatic

	column 金額
		dataType: double
		formatString: #,##0
		lineageTag: 2b52cda0-7f42-4214-8c04-6c6d49e9bc0d
		summarizeBy: sum
		sourceColumn: 金額

		annotation SummarizationSetBy = Automatic

	column 仕入単価
		dataType: double
		formatString: #,##0.00
		lineageTag: d91a99f3-eb8c-4d82-b818-264b49c0507b
		summarizeBy: none
		sourceColumn: 仕入単価

		annotation SummarizationSetBy = Automatic

	column 仕入原価推定
		dataType: double
		formatString: #,##0
		lineageTag: 8b628d57-f1c0-4b68-805c-b0a79b653c36
		summarizeBy: sum
		sourceColumn: 仕入原価推定

		annotation SummarizationSetBy = Automatic

	column 仕入年月
		dataType: string
		lineageTag: 5e1d9856-1315-47db-830b-5ab48e182180
		summarizeBy: none
		sourceColumn: 仕入年月

		annotation SummarizationSetBy = Automatic

	column 採用方式
		dataType: string
		lineageTag: e956c23c-ef9f-4d25-954c-0e63c12f4733
		summarizeBy: none
		sourceColumn: 採用方式

		annotation SummarizationSetBy = Automatic

	column 最高単価
		dataType: double
		formatString: #,##0.00
		lineageTag: 4a8731b9-29b3-41b6-b259-4996762d4702
		summarizeBy: none
		sourceColumn: 最高単価

		annotation SummarizationSetBy = Automatic

	column 最安単価
		dataType: double
		formatString: #,##0.00
		lineageTag: 5ca32a14-7f94-4ba6-b228-7cd1ee7fe641
		summarizeBy: none
		sourceColumn: 最安単価

		annotation SummarizationSetBy = Automatic

	column 平均単価
		dataType: double
		formatString: #,##0.00
		lineageTag: b1e1607a-1e29-4ced-9b01-2760bf7347f0
		summarizeBy: none
		sourceColumn: 平均単価

		annotation SummarizationSetBy = Automatic

	column 仕入契約単価
		dataType: double
		formatString: #,##0.00
		lineageTag: 5c299f36-36c8-42f8-87db-a4fb2b455426
		summarizeBy: none
		sourceColumn: 仕入契約単価

		annotation SummarizationSetBy = Automatic

	column 契約仕入原価推定
		dataType: double
		formatString: #,##0
		lineageTag: 7d4ee962-ce96-441a-a53c-2ffda8535c99
		summarizeBy: sum
		sourceColumn: 契約仕入原価推定

		annotation SummarizationSetBy = Automatic

	column 仕入先区分
		dataType: string
		lineageTag: ea3ee99e-6e29-4e2e-ac65-a3ebab4b0e7e
		summarizeBy: none
		sourceColumn: 仕入先区分

		annotation SummarizationSetBy = Automatic

	column 仕入先略称
		dataType: string
		lineageTag: e9eabfb4-825b-4f39-a08c-f1baa6692dfc
		summarizeBy: none
		sourceColumn: 仕入先略称

		annotation SummarizationSetBy = Automatic

	column 仕入単価有無
		dataType: string
		lineageTag: 2aaeb2c1-79a2-4783-8919-187542cf7eda
		summarizeBy: none
		sourceColumn: 仕入単価有無

		annotation SummarizationSetBy = Automatic

	column 仕入契約単価有無
		dataType: string
		lineageTag: fbc8cd75-e48f-4efc-a235-df035230d498
		summarizeBy: none
		sourceColumn: 仕入契約単価有無

		annotation SummarizationSetBy = Automatic

	column 概算単価
		dataType: double
		formatString: #,##0.00
		lineageTag: 4d7b41de-b89e-43fb-bb8b-641df3d8e46a
		summarizeBy: none
		sourceColumn: 概算単価

		annotation SummarizationSetBy = Automatic

	column 概算仕入原価推定
		dataType: double
		formatString: #,##0
		lineageTag: 771cabc3-1837-4104-a6f8-5257bf109976
		summarizeBy: sum
		sourceColumn: 概算仕入原価推定

		annotation SummarizationSetBy = Automatic

	column 概算原価算出方式
		dataType: string
		lineageTag: f3a7a9db-a52d-4454-9fd9-f7c133f81910
		summarizeBy: none
		sourceColumn: 概算原価算出方式

		annotation SummarizationSetBy = Automatic

	partition Fact_売上実績 = m
		mode: import
		source =
				let
				    Raw = Value.NativeQuery(Oracle.Database("(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=banshu-srv)(PORT=1521))(CONNECT_DATA=(SERVICE_NAME=prones)))"), "SELECT * FROM ( WITH items AS (SELECT DISTINCT TRIM(F_在庫品目番号) AS 品目コード FROM PRONES.TB_売上実績新情報 WHERE F_売上日 >= '2023/07/01'), months AS (SELECT TO_CHAR(ADD_MONTHS(DATE '2017-01-01', LEVEL-1),'YYYY/MM') AS 年月, ADD_MONTHS(DATE '2017-01-01', LEVEL-1) AS 年月日付 FROM DUAL CONNECT BY LEVEL <= 115), grid AS (SELECT i.品目コード, m.年月, m.年月日付 FROM items i CROSS JOIN months m), purchase_monthly AS (SELECT TRIM(F_品目番号) AS 品目コード, F_勘定年月 AS 年月, TO_DATE(F_勘定年月,'YYYY/MM') AS 年月日付, SUM(F_仕入数) AS 仕入数量, SUM(F_金額) AS 仕入金額, CASE WHEN SUM(F_仕入数)<>0 THEN SUM(F_金額)/SUM(F_仕入数) END AS 単月単価, MAX(CASE WHEN F_仕入数<>0 THEN F_金額/F_仕入数 END) AS 単月内最高単価, MIN(CASE WHEN F_仕入数<>0 THEN F_金額/F_仕入数 END) AS 単月内最安単価, AVG(CASE WHEN F_仕入数<>0 THEN F_金額/F_仕入数 END) AS 単月内単純平均単価 FROM PRONES.TB_仕入実績情報 GROUP BY TRIM(F_品目番号), F_勘定年月), windowed AS (SELECT g.品目コード, g.年月, CASE WHEN SUM(pm.仕入数量) IS NOT NULL AND SUM(pm.仕入数量)<>0 THEN SUM(pm.仕入金額)/SUM(pm.仕入数量) END AS 有効仕入単価_6mo, MAX(pm.単月単価) AS 窓内最高単価, MIN(pm.単月単価) AS 窓内最安単価 FROM grid g LEFT JOIN purchase_monthly pm ON pm.品目コード = g.品目コード AND pm.年月日付 BETWEEN ADD_MONTHS(g.年月日付,-5) AND g.年月日付 GROUP BY g.品目コード, g.年月), carried AS (SELECT g.品目コード, g.年月, LAST_VALUE(pm.単月単価 IGNORE NULLS) OVER (PARTITION BY g.品目コード ORDER BY g.年月日付) AS 有効仕入単価_carry, LAST_VALUE(CASE WHEN pm.単月単価 IS NOT NULL THEN pm.年月 END IGNORE NULLS) OVER (PARTITION BY g.品目コード ORDER BY g.年月日付) AS 単月仕入年月, LAST_VALUE(pm.単月内最高単価 IGNORE NULLS) OVER (PARTITION BY g.品目コード ORDER BY g.年月日付) AS 単月最高単価, LAST_VALUE(pm.単月内最安単価 IGNORE NULLS) OVER (PARTITION BY g.品目コード ORDER BY g.年月日付) AS 単月最安単価, LAST_VALUE(pm.単月内単純平均単価 IGNORE NULLS) OVER (PARTITION BY g.品目コード ORDER BY g.年月日付) AS 単月平均単価 FROM grid g LEFT JOIN purchase_monthly pm ON pm.品目コード = g.品目コード AND pm.年月日付 = g.年月日付), purchase_by_supplier AS (SELECT TRIM(F_品目番号) AS 品目コード, F_勘定年月 AS 年月, TO_DATE(F_勘定年月,'YYYY/MM') AS 年月日付, TRIM(F_指示先番号) AS 仕入先番号, SUM(F_金額) AS 金額 FROM PRONES.TB_仕入実績情報 GROUP BY TRIM(F_品目番号), F_勘定年月, TRIM(F_指示先番号)), supplier_name AS (SELECT TRIM(F_仕入先番号) AS 仕入先番号, MAX(F_仕入先略称) AS 仕入先略称 FROM PRONES.TB_仕入先情報 GROUP BY TRIM(F_仕入先番号)), windowed_sup AS (SELECT g.品目コード, g.年月, COUNT(DISTINCT pbs.仕入先番号) AS 件数, MAX(pbs.仕入先番号) AS 単一仕入先 FROM grid g LEFT JOIN purchase_by_supplier pbs ON pbs.品目コード = g.品目コード AND pbs.年月日付 BETWEEN ADD_MONTHS(g.年月日付,-5) AND g.年月日付 GROUP BY g.品目コード, g.年月), carried_sup AS (SELECT c.品目コード, c.年月, COUNT(DISTINCT pbs.仕入先番号) AS 件数, MAX(pbs.仕入先番号) AS 単一仕入先 FROM carried c LEFT JOIN purchase_by_supplier pbs ON pbs.品目コード = c.品目コード AND pbs.年月 = c.単月仕入年月 GROUP BY c.品目コード, c.年月), final_price AS (SELECT w.品目コード, w.年月, COALESCE(w.有効仕入単価_6mo, c.有効仕入単価_carry) AS 有効仕入単価, CASE WHEN w.有効仕入単価_6mo IS NOT NULL THEN w.年月 ELSE c.単月仕入年月 END AS 仕入年月, CASE WHEN w.有効仕入単価_6mo IS NOT NULL THEN w.窓内最高単価 ELSE c.単月最高単価 END AS 最高単価, CASE WHEN w.有効仕入単価_6mo IS NOT NULL THEN w.窓内最安単価 ELSE c.単月最安単価 END AS 最安単価, CASE WHEN w.有効仕入単価_6mo IS NOT NULL THEN w.有効仕入単価_6mo ELSE c.単月平均単価 END AS 平均単価, CASE WHEN w.有効仕入単価_6mo IS NOT NULL THEN '6ヶ月平均' WHEN c.有効仕入単価_carry IS NOT NULL THEN '単月' END AS 採用方式, CASE WHEN w.有効仕入単価_6mo IS NOT NULL THEN CASE WHEN ws.件数 = 1 THEN snw.仕入先略称 WHEN ws.件数 > 1 THEN '*' END ELSE CASE WHEN cs.件数 = 1 THEN snc.仕入先略称 WHEN cs.件数 > 1 THEN '*' END END AS 仕入略称 FROM windowed w JOIN carried c ON c.品目コード = w.品目コード AND c.年月 = w.年月 LEFT JOIN windowed_sup ws ON ws.品目コード = w.品目コード AND ws.年月 = w.年月 LEFT JOIN carried_sup cs ON cs.品目コード = w.品目コード AND cs.年月 = w.年月 LEFT JOIN supplier_name snw ON snw.仕入先番号 = ws.単一仕入先 LEFT JOIN supplier_name snc ON snc.仕入先番号 = cs.単一仕入先), contract_price AS (SELECT TRIM(F_納入品目番号) AS 品目コード, F_契約単価, CASE WHEN TRANSLATE(F_開始日,'0123456789','9999999999') = '9999/99/99' THEN TO_DATE(F_開始日,'YYYY/MM/DD') END AS 開始日付 FROM PRONES.TB_納入品目仕入先単価情報 WHERE F_契約単価 > 0), contract_ranked AS (SELECT g.品目コード, g.年月, cp.F_契約単価, ROW_NUMBER() OVER (PARTITION BY g.品目コード, g.年月 ORDER BY cp.開始日付 DESC) AS rn FROM grid g JOIN contract_price cp ON cp.品目コード = g.品目コード AND cp.開始日付 IS NOT NULL AND cp.開始日付 <= g.年月日付), contract_effective AS (SELECT 品目コード, 年月, F_契約単価 AS 仕入契約単価 FROM contract_ranked WHERE rn = 1), contract_price_2000001 AS (SELECT TRIM(F_納入品目番号) AS 品目コード, F_契約単価, CASE WHEN TRANSLATE(F_開始日,'0123456789','9999999999') = '9999/99/99' THEN TO_DATE(F_開始日,'YYYY/MM/DD') END AS 開始日付 FROM PRONES.TB_納入品目仕入先単価情報 WHERE F_契約単価 > 0 AND TRIM(F_仕入先番号) = '2000001'), contract_ranked_2000001 AS (SELECT g.品目コード, g.年月, cp.F_契約単価, ROW_NUMBER() OVER (PARTITION BY g.品目コード, g.年月 ORDER BY cp.開始日付 DESC) AS rn FROM grid g JOIN contract_price_2000001 cp ON cp.品目コード = g.品目コード AND cp.開始日付 IS NOT NULL AND cp.開始日付 <= g.年月日付), contract_effective_2000001 AS (SELECT 品目コード, 年月, F_契約単価 AS 仕入契約単価2000001 FROM contract_ranked_2000001 WHERE rn = 1), primary_supplier AS (SELECT 品目コード, 仕入先番号 FROM (SELECT TRIM(F_品目番号) AS 品目コード, TRIM(F_指示先番号) AS 仕入先番号, SUM(F_金額) AS 金額, ROW_NUMBER() OVER (PARTITION BY TRIM(F_品目番号) ORDER BY SUM(F_金額) DESC) AS rn FROM PRONES.TB_仕入実績情報 WHERE F_勘定年月 >= '2017/01' GROUP BY TRIM(F_品目番号), TRIM(F_指示先番号)) WHERE rn = 1) SELECT TRIM(s.F_得意先番号) AS 得意先番号, MAX(TRIM(s.F_得意先番号) || (chr(35)) || TO_CHAR(ORA_HASH(TRIM(s.F_得意先番号)))) AS 得意先キー, TRIM(s.F_在庫品目番号) AS 品目コード, SUBSTR(s.F_売上日,1,7) AS 年月, SUM(s.F_数量) AS 数量, SUM(s.F_金額) AS 金額, MAX(fp.有効仕入単価) AS 仕入単価, ROUND(SUM(s.F_数量) * MAX(fp.有効仕入単価)) AS 仕入原価推定, CASE WHEN MAX(fp.有効仕入単価) IS NOT NULL THEN 'あり' ELSE 'なし' END AS 仕入単価有無, MAX(fp.仕入年月) AS 仕入年月, MAX(fp.仕入略称) AS 仕入先略称, MAX(fp.採用方式) AS 採用方式, MAX(fp.最高単価) AS 最高単価, MAX(fp.最安単価) AS 最安単価, MAX(fp.平均単価) AS 平均単価, MAX(ce.仕入契約単価) AS 仕入契約単価, ROUND(SUM(s.F_数量) * MAX(ce.仕入契約単価)) AS 契約仕入原価推定, CASE WHEN MAX(ce.仕入契約単価) IS NOT NULL THEN 'あり' ELSE 'なし' END AS 仕入契約単価有無, CASE WHEN MAX(ps.仕入先番号) IS NULL THEN '仕入実績なし' WHEN MAX(ps.仕入先番号) IN ('2000001','2000002','2000004','2000005','2000006','2000007') THEN 'BEI' ELSE 'その他' END AS 仕入先区分, MAX(ce2.仕入契約単価2000001) AS 概算単価, CASE WHEN MAX(ce2.仕入契約単価2000001) IS NOT NULL THEN ROUND(SUM(s.F_数量) * MAX(ce2.仕入契約単価2000001)) ELSE ROUND(SUM(s.F_金額) * 0.85) END AS 概算仕入原価推定, CASE WHEN MAX(ce2.仕入契約単価2000001) IS NOT NULL THEN '仕入契約単価(2000001)' ELSE '売上高×85%' END AS 概算原価算出方式 FROM PRONES.TB_売上実績新情報 s LEFT JOIN final_price fp ON fp.品目コード = TRIM(s.F_在庫品目番号) AND fp.年月 = SUBSTR(s.F_売上日,1,7) LEFT JOIN contract_effective ce ON ce.品目コード = TRIM(s.F_在庫品目番号) AND ce.年月 = SUBSTR(s.F_売上日,1,7) LEFT JOIN contract_effective_2000001 ce2 ON ce2.品目コード = TRIM(s.F_在庫品目番号) AND ce2.年月 = SUBSTR(s.F_売上日,1,7) LEFT JOIN primary_supplier ps ON ps.品目コード = TRIM(s.F_在庫品目番号) WHERE s.F_売上日 >= '2023/07/01' GROUP BY TRIM(s.F_得意先番号), TRIM(s.F_在庫品目番号), SUBSTR(s.F_売上日,1,7) ) q"),
				    Source = Table.TransformColumnTypes(Raw, {{"仕入単価有無", type text}, {"数量", type number}, {"金額", type number}, {"仕入単価", type number}, {"仕入原価推定", type number}, {"仕入年月", type text}, {"仕入先略称", type text}, {"採用方式", type text}, {"最高単価", type number}, {"最安単価", type number}, {"平均単価", type number}, {"仕入契約単価", type number}, {"契約仕入原価推定", type number}, {"仕入契約単価有無", type text}, {"仕入先区分", type text}, {"概算単価", type number}, {"概算仕入原価推定", type number}, {"概算原価算出方式", type text}})
				in
				    Source

	annotation PBI_ResultType = Table

