table Fact_仕入実績
	lineageTag: 20ae447d-98e9-411a-a9bb-26c563e881bb

	column 品目コード
		dataType: string
		lineageTag: 12f79275-8740-4198-a8e6-631e029289a1
		summarizeBy: none
		sourceColumn: 品目コード

		annotation SummarizationSetBy = Automatic

	column 年月
		dataType: string
		lineageTag: cca636c5-e4fb-42a7-8c80-bf0c8d547e24
		summarizeBy: none
		sourceColumn: 年月

		annotation SummarizationSetBy = Automatic

	column 仕入数量
		dataType: double
		formatString: #,##0
		lineageTag: 4b0eeec0-cc51-4b72-bfa6-064a724d5ad0
		summarizeBy: sum
		sourceColumn: 仕入数量

		annotation SummarizationSetBy = Automatic

	column 仕入金額
		dataType: double
		formatString: #,##0
		lineageTag: bbcdf8ab-d93e-4859-8af3-17c392296de9
		summarizeBy: sum
		sourceColumn: 仕入金額

		annotation SummarizationSetBy = Automatic

	column 平均仕入単価
		dataType: double
		formatString: #,##0.00
		lineageTag: fe81692e-1f26-43a0-ab66-4e1938c9c8f6
		summarizeBy: none
		sourceColumn: 平均仕入単価

		annotation SummarizationSetBy = Automatic

	column 仕入先番号
		dataType: string
		lineageTag: 18eb6002-278f-4521-911b-74932a58e4e2
		summarizeBy: none
		sourceColumn: 仕入先番号

		annotation SummarizationSetBy = Automatic

	partition Fact_仕入実績 = m
		mode: import
		source =
				let
				    Raw = Value.NativeQuery(Oracle.Database("(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=banshu-srv)(PORT=1521))(CONNECT_DATA=(SERVICE_NAME=prones)))"), "SELECT * FROM ( WITH monthly_totals AS (SELECT TRIM(F_品目番号) AS 品目コード, F_勘定年月 AS 年月, SUM(F_仕入数) AS 仕入数量, SUM(F_金額) AS 仕入金額 FROM PRONES.TB_仕入実績情報 WHERE TRIM(F_品目番号) NOT IN ('99999','N-99999') GROUP BY TRIM(F_品目番号), F_勘定年月), top_supplier AS (SELECT 品目コード, 年月, 仕入先番号 FROM (SELECT TRIM(F_品目番号) AS 品目コード, F_勘定年月 AS 年月, TRIM(F_指示先番号) AS 仕入先番号, SUM(F_金額) AS 金額, ROW_NUMBER() OVER (PARTITION BY TRIM(F_品目番号), F_勘定年月 ORDER BY SUM(F_金額) DESC) AS rn FROM PRONES.TB_仕入実績情報 WHERE TRIM(F_品目番号) NOT IN ('99999','N-99999') GROUP BY TRIM(F_品目番号), F_勘定年月, TRIM(F_指示先番号)) WHERE rn = 1) SELECT mt.品目コード, mt.年月, mt.仕入数量, mt.仕入金額, ROUND(mt.仕入金額/NULLIF(mt.仕入数量,0),2) AS 平均仕入単価, ts.仕入先番号 FROM monthly_totals mt LEFT JOIN top_supplier ts ON ts.品目コード = mt.品目コード AND ts.年月 = mt.年月 ) q"),
				    Source = Table.TransformColumnTypes(Raw, {{"仕入数量", type number}, {"仕入金額", type number}, {"平均仕入単価", type number}})
				in
				    Source

	annotation PBI_ResultType = Table

